[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/tmux-nerd-font-window-name"]
    type = "git-repo"
    url = "https://github.com/joshmedeski/tmux-nerd-font-window-name"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".config/tmux/plugins/catppuccin/tmux"]
    type = "archive"
    exact = true
    stripComponents = 1
    url = "https://github.com/catppuccin/tmux/archive/refs/tags/v2.1.3.tar.gz"
    refreshPeriod = "168h"

[".zsh_custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url =  "https://github.com/zsh-users/zsh-autosuggestions"
    refreshPeriod = "168h"

[".zsh_custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url =  "https://github.com/zsh-users/zsh-syntax-highlighting"
    refreshPeriod = "168h"

[".zsh_custom/plugins/fzf-tab"]
    type = "git-repo"
    url =  "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "168h"

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/BaktashGorgani/nvim-config.git"
    refreshPeriod = "24h"
